import AppKit
import SwiftUI
import Combine

/// Un tipo de dato dentro del portapapeles (texto, RTF, imagen, archivo…).
struct ClipEntry: Codable {
    let type: String
    let data: Data
}

/// Una "foto" completa del portapapeles. Guarda todos los formatos para que,
/// al pegarlo, se pegue igual que el original (con formato, imagen, archivos…).
struct ClipItem: Identifiable, Codable {
    enum Kind: String, Codable {
        case text, image, files, other

        var symbol: String {
            switch self {
            case .text: return "text.alignleft"
            case .image: return "photo"
            case .files: return "doc.on.doc"
            case .other: return "square.stack.3d.up"
            }
        }
    }

    var id = UUID()
    var date = Date()
    var items: [[ClipEntry]]
    var kind: Kind
    var preview: String
    var signature: String

    private static let imageTypes: Set<String> = [
        "public.png", "public.tiff", "public.jpeg", "com.compuserve.gif", "public.heic"
    ]

    /// Tipos que usan los gestores de contraseñas para pedir "no me guardes".
    private static let privacyMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType"
    ]

    /// Si algo es enorme, nos quedamos solo con estos formatos.
    private static let essentialTypes: Set<String> = [
        "public.utf8-plain-text", "public.rtf", "public.html",
        "public.file-url", "public.url", "public.png", "public.jpeg"
    ]

    private static let maxBytes = 12 * 1024 * 1024

    var imageData: Data? {
        for group in items {
            for entry in group where ClipItem.imageTypes.contains(entry.type) {
                return entry.data
            }
        }
        return nil
    }

    /// Modo capturas: un texto o una imagen de ejemplo, como si los hubieras copiado.
    static func demo(texto: String, hace segundos: TimeInterval = 0) -> ClipItem {
        var item = make(from: [[ClipEntry(type: "public.utf8-plain-text", data: Data(texto.utf8))]])
        item.date = Date().addingTimeInterval(-segundos)
        return item
    }

    static func demo(png: Data, hace segundos: TimeInterval = 0) -> ClipItem {
        var item = make(from: [[ClipEntry(type: "public.png", data: png)]])
        item.date = Date().addingTimeInterval(-segundos)
        return item
    }

    // MARK: Leer del portapapeles

    static func capture(from pasteboard: NSPasteboard, respectPrivacy: Bool) -> ClipItem? {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else { return nil }

        var allTypes = Set<String>()
        for item in pasteboardItems {
            for type in item.types { allTypes.insert(type.rawValue) }
        }
        if respectPrivacy && !allTypes.isDisjoint(with: privacyMarkers) { return nil }

        var groups: [[ClipEntry]] = []
        for pasteboardItem in pasteboardItems {
            var entries: [ClipEntry] = []
            for type in pasteboardItem.types {
                if let data = pasteboardItem.data(forType: type) {
                    entries.append(ClipEntry(type: type.rawValue, data: data))
                }
            }
            if !entries.isEmpty { groups.append(entries) }
        }

        if totalBytes(groups) > maxBytes {
            groups = groups
                .map { group in group.filter { essentialTypes.contains($0.type) } }
                .filter { !$0.isEmpty }
        }
        guard !groups.isEmpty, totalBytes(groups) <= maxBytes else { return nil }
        return make(from: groups)
    }

    private static func totalBytes(_ groups: [[ClipEntry]]) -> Int {
        var total = 0
        for group in groups {
            for entry in group { total += entry.data.count }
        }
        return total
    }

    private static func make(from groups: [[ClipEntry]]) -> ClipItem {
        let size = totalBytes(groups)

        var fileNames: [String] = []
        var plainText: String?
        var hasImage = false
        for group in groups {
            for entry in group {
                if entry.type == "public.file-url",
                   let raw = String(data: entry.data, encoding: .utf8) {
                    let cleaned = raw.trimmingCharacters(in: CharacterSet(charactersIn: "\0").union(.whitespacesAndNewlines))
                    if let url = URL(string: cleaned) { fileNames.append(url.lastPathComponent) }
                }
                if plainText == nil, entry.type == "public.utf8-plain-text" {
                    plainText = String(data: entry.data, encoding: .utf8)
                }
                if imageTypes.contains(entry.type) { hasImage = true }
            }
        }

        let kind: Kind
        let preview: String
        if !fileNames.isEmpty {
            kind = .files
            preview = fileNames.count == 1
                ? fileNames[0]
                : "\(fileNames.count) archivos: " + fileNames.joined(separator: ", ")
        } else if let text = plainText {
            kind = .text
            let head = String(text.prefix(2000))
            let collapsed = head
                .components(separatedBy: .whitespacesAndNewlines)
                .filter { !$0.isEmpty }
                .joined(separator: " ")
            preview = collapsed.isEmpty ? "(texto en blanco)" : String(collapsed.prefix(240))
        } else if hasImage {
            kind = .image
            preview = "Imagen · " + ByteCountFormatter.string(fromByteCount: Int64(size), countStyle: .file)
        } else {
            kind = .other
            preview = groups.first?.first?.type ?? "Contenido"
        }

        let signature = "\(kind.rawValue)|\(size)|\(preview.prefix(120))"
        return ClipItem(items: groups, kind: kind, preview: preview, signature: signature)
    }

    // MARK: Escribir al portapapeles

    func write(to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        var objects: [NSPasteboardItem] = []
        for group in items {
            let pasteboardItem = NSPasteboardItem()
            for entry in group {
                pasteboardItem.setData(entry.data, forType: NSPasteboard.PasteboardType(entry.type))
            }
            objects.append(pasteboardItem)
        }
        pasteboard.writeObjects(objects)
    }
}

/// Multiportapapeles: historial automático + 9 ranuras fijas (se guardan en disco).
@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var history: [ClipItem] = []
    @Published private(set) var slots: [Int: ClipItem] = [:]
    @Published var shortcutsActive = false

    /// Para mostrar avisos en la isla.
    var onEvent: ((Peek) -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var pollTimer: AnyCancellable?
    private var restoreTask: Task<Void, Never>?
    private var restoreBackup: ClipItem?
    private var thumbCache: [UUID: NSImage] = [:]
    private let maxHistory = 30
    private let slotsURL: URL

    init() {
        slotsURL = AppPaths.support.appendingPathComponent("ranuras.plist")
        // Modo capturas: sin leer tu portapapeles ni tus ranuras.
        if ModoCapturas.activo {
            lastChangeCount = 0
            return
        }
        lastChangeCount = NSPasteboard.general.changeCount
        loadSlots()
        pollTimer = Timer.publish(every: 0.4, on: .main, in: .common)
            .autoconnect()
            .sink { [weak self] _ in
                self?.poll()
            }
    }

    /// Modo capturas: historial y ranuras de ejemplo (no se guardan).
    func cargarDemo(historial: [ClipItem], ranuras: [Int: ClipItem]) {
        history = historial
        slots = ranuras
    }

    // MARK: Historial

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard let item = ClipItem.capture(from: pasteboard, respectPrivacy: true) else { return }
        history.removeAll { $0.signature == item.signature }
        history.insert(item, at: 0)
        if history.count > maxHistory {
            history.removeLast(history.count - maxHistory)
        }
        trimThumbCache()
    }

    func copyToPasteboard(_ item: ClipItem, message: String = "Copiado · ⌘V para pegar") {
        item.write(to: pasteboard)
        onEvent?(Peek(symbol: "doc.on.clipboard.fill", title: message, tint: Theme.accent))
    }

    func removeFromHistory(_ item: ClipItem) {
        history.removeAll { $0.id == item.id }
        trimThumbCache()
    }

    func clearHistory() {
        history.removeAll()
        trimThumbCache()
    }

    // MARK: Ranuras

    /// Después de ⌘C + número: espera a que la app termine de copiar y guarda.
    func saveAfterCopy(slot: Int, baseline: Int) {
        Task { [weak self] in
            for _ in 0..<12 {
                guard let strongSelf = self else { return }
                if strongSelf.pasteboard.changeCount != baseline { break }
                try? await Task.sleep(nanoseconds: 80_000_000)
            }
            try? await Task.sleep(nanoseconds: 60_000_000)
            self?.saveCurrentClipboard(toSlot: slot)
        }
    }

    func saveCurrentClipboard(toSlot slot: Int) {
        guard let item = ClipItem.capture(from: pasteboard, respectPrivacy: false) else {
            onEvent?(Peek(symbol: "exclamationmark.circle.fill", title: "Nada que guardar", tint: Theme.warning))
            return
        }
        save(item, toSlot: slot)
    }

    func save(_ item: ClipItem, toSlot slot: Int) {
        var copy = item
        copy.id = UUID()
        copy.date = Date()
        slots[slot] = copy
        saveSlots()
        onEvent?(Peek(symbol: "\(slot).circle.fill", title: "Guardado en ranura \(slot)", tint: Theme.accent))
    }

    func clearSlot(_ slot: Int) {
        slots[slot] = nil
        saveSlots()
        trimThumbCache()
    }

    func clearAllSlots() {
        slots.removeAll()
        saveSlots()
        trimThumbCache()
    }

    /// ⌘V + número: pone la ranura en el portapapeles, "teclea" ⌘V y
    /// después regresa lo que tenías copiado antes.
    func pasteSlot(_ slot: Int) {
        guard let item = slots[slot] else {
            onEvent?(Peek(symbol: "\(slot).circle", title: "Ranura \(slot) vacía", tint: Theme.warning))
            return
        }

        let backup: ClipItem?
        if let pending = restoreTask {
            pending.cancel()
            backup = restoreBackup
        } else {
            backup = ClipItem.capture(from: pasteboard, respectPrivacy: false)
        }

        item.write(to: pasteboard)
        let written = pasteboard.changeCount
        lastChangeCount = written
        KeyInterceptor.postCommandV()
        onEvent?(Peek(symbol: "\(slot).circle.fill", title: "Pegado desde ranura \(slot)", tint: Theme.accent))

        restoreBackup = backup
        restoreTask = Task { [weak self] in
            try? await Task.sleep(nanoseconds: 700_000_000)
            guard !Task.isCancelled, let strongSelf = self else { return }
            strongSelf.finishRestore(expectedChangeCount: written)
        }
    }

    private func finishRestore(expectedChangeCount: Int) {
        let backup = restoreBackup
        restoreTask = nil
        restoreBackup = nil
        // Si mientras tanto copiaste otra cosa, no la pisamos.
        guard pasteboard.changeCount == expectedChangeCount else { return }
        if let backup = backup {
            backup.write(to: pasteboard)
        } else {
            pasteboard.clearContents()
        }
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: Miniaturas de imágenes

    func thumbnail(for item: ClipItem) -> NSImage? {
        if let cached = thumbCache[item.id] { return cached }
        guard let data = item.imageData, let image = NSImage(data: data) else { return nil }
        thumbCache[item.id] = image
        return image
    }

    private func trimThumbCache() {
        var alive = Set(history.map { $0.id })
        for item in slots.values { alive.insert(item.id) }
        thumbCache = thumbCache.filter { alive.contains($0.key) }
    }

    // MARK: Guardar ranuras en disco

    private func saveSlots() {
        var dictionary: [String: ClipItem] = [:]
        for (key, value) in slots { dictionary[String(key)] = value }
        do {
            let data = try PropertyListEncoder().encode(dictionary)
            try data.write(to: slotsURL, options: .atomic)
        } catch {
            NSLog("UltraNotch: no se pudieron guardar las ranuras: \(error.localizedDescription)")
        }
    }

    private func loadSlots() {
        guard let data = try? Data(contentsOf: slotsURL),
              let dictionary = try? PropertyListDecoder().decode([String: ClipItem].self, from: data) else { return }
        var result: [Int: ClipItem] = [:]
        for (key, value) in dictionary {
            if let number = Int(key), (1...9).contains(number) { result[number] = value }
        }
        slots = result
    }
}
